#include<sys/types.h>
#include<sys/wait.h>
#include<unistd.h>
#include<stdlib.h>
#include<string.h>
#include<stdio.h>
#include<fcntl.h>
#include<errno.h>

void cd_command(char *input,char *input1){
	char cwd[1000];
	getcwd(cwd,sizeof cwd);
	
	if(input==NULL || strcmp(input,"~")==0 || strcmp(input,"-P")==0){
		char *home=getenv("HOME");
		chdir(home);
		if(errno==ENOENT){
			printf("%s\n","The directory specified in path does not exist." );
		}
		else if(errno==EACCES){
			printf("%s\n","Search permission is denied for one of the components of path." );
		}
	}
	else if(strcmp(input,"-L")==0){
		int x=chdir(input1);
		if(x<0){
			//printf("cd: %s: No such file or directory\n",input );
			if(errno==ENOENT){
			printf("%s\n","The directory specified in path does not exist." );
			}
			else if(errno==EACCES){
				printf("%s\n","Search permission is denied for one of the components of path." );
			}
		}
	}
	else if(strcmp(input,"..")==0){
		chdir("../");
		if(errno==ENOENT){
			printf("%s\n","The directory specified in path does not exist." );
		}
		else if(errno==EACCES){
			printf("%s\n","Search permission is denied for one of the components of path." );
		}
	}
	else{
		int x=chdir(input);
		if(x<0){
			//printf("cd: %s: No such file or directory\n",input );
			if(errno==ENOENT){
			printf("%s\n","The directory specified in path does not exist." );
			}
			else if(errno==EACCES){
				printf("%s\n","Search permission is denied for one of the components of path." );
			}
		}
	}
	getcwd(cwd,sizeof cwd);
	printf("%s\n",cwd );
	
}


void pwd_command(char *input){
	if(input==NULL || strcmp(input,"-L")==0){
		char cwd[1000];
		getcwd(cwd,sizeof cwd);
		if(errno==ENOENT){
			printf("%s\n","The current working directory has been unlinked." );
		}
		else if(errno==EACCES){
			printf("%s\n","Permission to read or search a component of the filename was denied." );
		}
		printf("%s\n",cwd );
	}
	else if(strcmp(input,"-P")==0){
		char *home=getenv("HOME");
		printf("%s\n",home );
	}
	else{
		if(strcmp(input,"--help")==0){
			printf("%s\n","pwd: pwd [-LP]\nPrint the name of the current working directory.\n\n Options:\n-L     print the value of $PWD if it names the current working\ndirectory\n-P    print the physical directory, without any symbolic links\n\nBy default, `pwd' behaves as if `-L' were specified.\n\nExit Status:\nReturns 0 unless an invalid option is given or the current directory\ncannot be read.\n");
		}//add more condition
	}
}


void exit_command(){
	exit(0);
}


void echo_command(char *input1, char *input2){
	if(input1==NULL){
		printf("\n");
	}
	else if(strcmp(input1,"-n")==0){
		int i=0;
		while(input2[i]!='\0'){
			if(input2[i]=='\n'){
				i++;
			}
			else{
				printf("%c",input2[i]);//make some changes
				i++;
			}
		}
		//write(STDOUT_FILENO,input2,strlen(input2));
	}
	else if(strcmp(input1,"-E")==0){
		int i=0;
		while(i<strlen(input2) && input2[i]!='\0'){
			if(input2[i]=='\a'){
				i++;
			}
			else if(input2[i]=='\b'){
				i++;
			}
			else if(input2[i]=='\e'){
				i++;
			}
			else if(input2[i]=='\f'){
				i++;
			}
			else if(input2[i]=='\n'){
				i++;
			}
			else if(input2[i]=='\r'){
				i++;
			}
			else if(input2[i]=='\t'){
				i++;
			}
			else if(input2[i]=='\v'){
				i++;
			}
			else if(input2[i]=='\\'){
				i++;
			}
			
			else{
				printf("%c",input2[i]);
				//write(STDOUT_FILENO,input2[i],strlen(input2[i]));
				i++;
			}
		}
	}
	else{
		printf("%s\n",input1);
	}
}

void addHist(char *input){
	FILE *f=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","a");
	if(f!=NULL){
		fprintf(f, "%s\n",input);
	}
	fclose(f);
}

void history_command(char *input,char *input1){
	if(input==NULL){
		FILE *f=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","r");
		if(f!=NULL){
			char line[200];
			int i=1;
			while(fgets(line,sizeof line,f)!=NULL){
				printf("%d.   %s\n",i,line );
				i++;
			}
		}
		perror("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt");//handles all errors based on all errnos generated by fopen
		fclose(f);
	}
	else if(strcmp(input,"-c")==0){
		FILE *f=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","w");
		perror("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt");
		fclose(f);
	}
	else if(strcmp(input,"-s")==0){
		FILE *f=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","a");
		if(f!=NULL){
		fprintf(f, "%s\n",input1);
		}
		perror("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt");
		fclose(f);
	}
	/*else if(strcmp(input,"-d")==0){
		//delete input1 - 1,since one more entry is added
		//printf("%s\n","hiiii" );
		int x=atoi(input1);
		//printf("%d\n", x);
		FILE *fi=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","r");
		int count=0;
		if(fi!=NULL){
			char line[200];
			while(fgets(line,sizeof line,fi)!=NULL){
				count++;
			}
		}
		//printf("%d    %s\n",count,"count" );
		perror("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt");
		fclose(fi);
		if(x>0 && x<=count){

		}
		else if(x<0){
			//printf("%s\n","ajao" );
			//int d=x-2;
			int y=(count+x+1);//to make it work like actaul delete in bash;
			x=y;
		}
		else if(x>count || x==0){
			x=0;
		}
		//printf("%d   %s\n",x,"hello" );
		FILE *f=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","r");
		FILE *f1=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history1.txt","w");
		if(f!=NULL && f1!=NULL){
			char line[200];
			int i=1;
			while(fgets(line,sizeof line,f)!=NULL){
				//printf("%d.   %s\n",i,line );
				if(i==x){
					//fprintf(f1, "%s\n",line);
				}
				else{
					fprintf(f1, "%s",line);
				}
				i++;
			}
		}
		fclose(f);
		fclose(f1);
		int l=remove("history.txt");
		/*if(l==0){
			printf("%s\n","thank" );
		}*/
		//int ret=rename("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history1.txt","history.txt");
		/*if(ret==0){
			printf("%s\n","yessss" );
		}*/

	//}*/
	else{
		int val=atoi(input);//also handles the case when a number is not passed since it atoi will return 0
		FILE *fi=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","r");
		int count=0;
		if(fi!=NULL){
			char line[200];
			while(fgets(line,sizeof line,fi)!=NULL){
				count++;
			}
		}
		perror("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt");
		fclose(fi);
		FILE *f=fopen("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt","r");
		if(f!=NULL){
			char line[200];
			int x=0;
			while(fgets(line,sizeof line,f)!=NULL){
				if(x>=(count-val)){
					printf("%d.   %s\n",x,line );
					x++;
				}
				else{
					x++;
				}
			}
		}
		perror("/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/history.txt");
		fclose(f);
	}
}

void main(){
	char input[500];
	printf("%s\n","Welcome to the Shell>>>>" );
	//the %[^\n]%*c makes it read the input including scpaces until \n charachter,
							  //otherwise it would have read till space

	//add command to history
	while(1){
		printf("%s",">>" );
		scanf("%[^\n]%*c",input);
		addHist(input);
		char *sep_input[5];
		int i=0;
		sep_input[i]=strtok(input," ");//strtok returns a pointer to the location after " " in each successive call
		while(sep_input[i]!=NULL){
			i++;
			sep_input[i]=strtok(NULL," ");
		}
		char abc[1]="\n";/*
		if(sep_input[0]=="\n"){
			printf("%s\n","oops" );
		}*/
		if(strcmp(sep_input[0],abc)==0){
			printf("%s\n","oops" );
		}
		else if(strcmp(sep_input[0],"cd")==0){
			cd_command(sep_input[1],sep_input[2]);
		}
		else if(strcmp(sep_input[0],"pwd")==0){
			pwd_command(sep_input[1]);
		}
		else if(strcmp(sep_input[0],"echo")==0){
			echo_command(sep_input[1],sep_input[2]);
		}
		else if(strcmp(sep_input[0],"history")==0){
			history_command(sep_input[1],sep_input[2]);
		}
		else if(strcmp(sep_input[0],"exit")==0){
  			exit_command();
		}
		else{
			pid_t pid;
			pid=fork();
			if(pid<0){
				fprintf(stderr, "%s\n","Fork Failed" );
			}
			else if(pid==0){
				//to open any file,first compile it with the name gcc filename.c -o filename.o
				if(strcmp(sep_input[0],"date")==0 && sep_input[1]==NULL){
					//execl()
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/date.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);
				}
				else if(strcmp(sep_input[0],"date")==0 && strcmp(sep_input[1],"-R")==0 ){
					//execl()
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/date_R.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);
				}
				else if(strcmp(sep_input[0],"date")==0 && strcmp(sep_input[1],"-I")==0 ){
					//execl()
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/date_I.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);
				}
				else if(strcmp(sep_input[0],"mkdir")==0){
					//printf("%s\n", "success");
					//execl("./mkdir.o",sep_input[1],NULL);
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/mkdir.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);
				}
				else if(strcmp(sep_input[0],"rm")==0){
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/rm.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);
				}
				else if(strcmp(sep_input[0],"cat")==0){
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/cat.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);
				}
				else if(strcmp(sep_input[0],"ls")==0 && sep_input[1]==NULL){
					//printf("%s\n","okay" );
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/ls.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);	
				}
				else if(strcmp(sep_input[0],"ls")==0 && strcmp(sep_input[1],"-a")==0){
					//printf("%s\n","okay" );
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/ls_a.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);	
				}
				else if(strcmp(sep_input[0],"ls")==0 && strcmp(sep_input[1],"-1")==0){
					//printf("%s\n","okay" );
					char *args[]={"/mnt/c/users/dell/dipankar/sem3/os/ass1/q2/ls_1.o",sep_input[1],sep_input[2],NULL}; 
        			execv(args[0],args);	
				}
				exit(-1);
			}
			else{
				waitpid(-1,NULL,0);
			}
		}
	}
}